export const stockConstants = {
    SET_COMPANY: 'STOCK_ADD_COMPANY',
    GET_COMPANY: 'STOCK_GET_COMPANY',
    REQUEST_FAILURE: 'STOCK_GET_FAILURE',
    SET_CHART_DATA: 'SET_CHART_DATA',
    STOCK_CHART_LOADING: 'STOCK_CHART_LOADING'
};
